const fs = require('fs');
const path = require('path');

const rootDir = __dirname;

const vibeModuleFiles = [
  'shared/vibe/vibe-core.js',
  'shared/vibe/vibe-services.js',
  'shared/vibe/vibe-popover.js',
  'shared/vibe/vibe-context-menu.js',
  'shared/vibe/vibe-feed.js',
  'shared/vibe/vibe-section-ai.js',
  'shared/vibe/vibe-section-waves.js',
  'shared/vibe/vibe-section-instyle.js',
  'shared/vibe/vibe-section-releases.js',
  'shared/vibe/vibe-section-concerts.js',
  'shared/vibe/vibe-section-premiere.js',
  'shared/vibe/vibe-section-mixes.js',
  'shared/vibe/vibe-section-albums-month.js',
  'shared/vibe/vibe-button-debugger.js',
  'shared/vibe/vibe-init.js'
];

function bundleVibeStyles() {
  const stylesDir = path.join(rootDir, 'shared', 'vibe', 'styles');
  const cssFiles = [
    'vibe-base.css',
    'vibe-popover.css',
    'vibe-feed.css',
    'vibe-ai-waves.css',
    'vibe-instyle.css',
    'vibe-releases.css',
    'vibe-concerts.css',
    'vibe-premiere.css',
    'vibe-mixes.css',
    'vibe-albums-month.css',
    'vibe-context-menu.css'
  ];

  let combinedCss = '';
  for (const file of cssFiles) {
    const filePath = path.join(stylesDir, file);
    if (fs.existsSync(filePath)) {
      combinedCss += `/* === ${file} === */\n` + fs.readFileSync(filePath, 'utf8') + '\n\n';
    } else {
      console.warn(`Warning: Vibe CSS file not found: ${filePath}`);
    }
  }

  const destPath = path.join(rootDir, 'shared', 'vibe', 'vibe-styles.js');
  const jsContent = '/**\n * Better Yandex Music - Vibe Enhancer Styles\n * Auto-generated by build.js from shared/vibe/styles/*.css\n */\n\nfunction injectVibeStyles() {\n  if (document.getElementById(\'ym-vibe-styles\')) return;\n\n  const style = document.createElement(\'style\');\n  style.id = \'ym-vibe-styles\';\n  style.textContent = ' + JSON.stringify(combinedCss) + ';\n  document.head.appendChild(style);\n}\n\nif (typeof window !== \'undefined\') {\n  window.injectVibeStyles = injectVibeStyles;\n}\n';
  fs.writeFileSync(destPath, jsContent, 'utf8');
  console.log('Successfully bundled Vibe styles -> shared/vibe/vibe-styles.js');
}

function buildElectron() {
  console.log('Building Electron desktop-sync.js...');
  const electronSrcDir = path.join(rootDir, 'yandex-sync-electron', 'src');
  
  if (!fs.existsSync(electronSrcDir)) {
    console.error('Error: yandex-sync-electron/src does not exist');
    return false;
  }

  // Preload Context Files
  const preloadFiles = [
    'preload/variables.js',
    'preload/discord.js',
    'shared/md5.js',
    'shared/rzt-api.js',
    'shared/scrobbler.js',
    'preload/api-server.js',
    'shared/soundcloud-import.js',
    'preload/bridge.js'
  ];

  // Page Context Files
  const pageFiles = [
    'shared/styles.js',
    'shared/vibe/vibe-styles.js',
    'shared/rzt-api.js',
    'shared/genius-api.js',
    'page/variables.js',
    'shared/themes.js',
    'shared/scale-changer.js',
    'shared/navbar-sync.js',
    'shared/sync-popover.js',
    'shared/theme-popover.js',
    'shared/sleep-timer.js',
    'shared/settings-injector.js',
    'shared/wrapped/chart.js',
    'shared/wrapped/wrapped-ui.js',
    'shared/wrapped/wrapped-db.js',
    'shared/wrapped/wrapped-tracker.js',
    'shared/wrapped/wrapped-charts.js',
    'shared/wrapped/wrapped-stories.js',
    'shared/quality-indicator.js',
    'shared/track-downloader.js',
    'shared/lyrics/lrclib-client.js',
    'shared/lyrics/lyrics-sidebar.js',
    'shared/lyrics/lyrics-highlight.js',
    'shared/fullscreen/fullscreen-utils.js',
    'shared/fullscreen/fullscreen-lyrics.js',
    'shared/translation/translation.js',
    'page/socket-client.js',
    'page/player-monitor.js',
    'shared/soundcloud-api.js',
    'shared/custom-audio.js',
    'shared/player-faker.js',
    'shared/soundcloud-search.js',
    'shared/release-notes.js',
    ...vibeModuleFiles,
    'page/index.js'
  ];

  let preloadCode = '';
  for (const file of preloadFiles) {
    const filePath = file.startsWith('shared/') ? path.join(rootDir, file) : path.join(electronSrcDir, file);
    if (!fs.existsSync(filePath)) {
      console.error(`Error: Preload component file ${file} not found at ${filePath}`);
      return false;
    }
    preloadCode += `// --- Component: ${file} ---\n` + fs.readFileSync(filePath, 'utf8') + '\n\n';
  }

  let pageCode = '';
  for (const file of pageFiles) {
    const filePath = file.startsWith('shared/') ? path.join(rootDir, file) : path.join(electronSrcDir, file);
    if (!fs.existsSync(filePath)) {
      console.error(`Error: Page component file ${file} not found at ${filePath}`);
      return false;
    }
    pageCode += `// --- Component: ${file} ---\n` + fs.readFileSync(filePath, 'utf8') + '\n\n';
  }

  const combinedCode = `(function() {
  console.log("[SYNC] Yandex Music Sync (Electron Desktop) запущен!");

  if (typeof require !== 'undefined') {
    // ==========================================
    // PRELOAD NODE CONTEXT (Discord RPC & HTTP Server)
    // ==========================================
${preloadCode.split('\n').map(line => '    ' + line).join('\n')}
    return;
  }

  // ==========================================
  // WEB PAGE CONTEXT (Browser logic)
  // ==========================================
${pageCode}
})();
`;

  const destPath = path.join(rootDir, 'yandex-sync-electron', 'desktop-sync.js');
  fs.writeFileSync(destPath, combinedCode, 'utf8');
  console.log(`Successfully built Electron desktop-sync.js -> ${destPath}`);

  // Also copy to installer assets
  const installerAssetsDir = path.join(rootDir, 'yandex-sync-installer', 'assets');
  if (fs.existsSync(installerAssetsDir)) {
    const installerDestPath = path.join(installerAssetsDir, 'desktop-sync.js');
    fs.writeFileSync(installerDestPath, combinedCode, 'utf8');
    console.log(`Successfully copied desktop-sync.js -> ${installerDestPath}`);
  }
  return true;
}

function buildExtension() {
  console.log('Building Extension scripts...');
  const extSrcDir = path.join(rootDir, 'yandex-sync-extension', 'src');

  if (!fs.existsSync(extSrcDir)) {
    console.error('Error: yandex-sync-extension/src does not exist');
    return false;
  }

  // Isolated Context Files
  const isolatedFiles = [
    'shared/styles.js',
    'shared/vibe/vibe-styles.js',
    'shared/md5.js',
    'shared/rzt-api.js',
    'shared/genius-api.js',
    'shared/scrobbler.js',
    'isolated/scrobbler-init.js',
    'isolated/variables.js',
    'shared/themes.js',
    'shared/navbar-sync.js',
    'shared/sync-popover.js',
    'shared/theme-popover.js',
    'shared/sleep-timer.js',
    'shared/quality-indicator.js',
    'shared/lyrics/lrclib-client.js',
    'shared/lyrics/lyrics-sidebar.js',
    'shared/lyrics/lyrics-highlight.js',
    'shared/fullscreen/fullscreen-utils.js',
    'shared/fullscreen/fullscreen-lyrics.js',
    'shared/translation/translation.js',
    'isolated/socket-client.js',
    'isolated/index.js'
  ];

  // Main Context Files
  const mainFiles = [
    'shared/vibe/vibe-styles.js',
    'main/variables.js',
    'main/player-monitor.js',
    'shared/scale-changer.js',
    'shared/settings-injector.js',
    'shared/wrapped/chart.js',
    'shared/wrapped/wrapped-ui.js',
    'shared/wrapped/wrapped-db.js',
    'shared/wrapped/wrapped-tracker.js',
    'shared/wrapped/wrapped-charts.js',
    'shared/wrapped/wrapped-stories.js',
    'shared/soundcloud-api.js',
    'shared/custom-audio.js',
    'shared/player-faker.js',
    'shared/soundcloud-search.js',
    'shared/track-downloader.js',
    'shared/release-notes.js',
    ...vibeModuleFiles,
    'main/index.js'
  ];

  let isolatedCode = '';
  for (const file of isolatedFiles) {
    const filePath = file.startsWith('shared/') ? path.join(rootDir, file) : path.join(extSrcDir, file);
    if (!fs.existsSync(filePath)) {
      console.error(`Error: Isolated component file ${file} not found at ${filePath}`);
      return false;
    }
    isolatedCode += `// --- Component: ${file} ---\n` + fs.readFileSync(filePath, 'utf8') + '\n\n';
  }

  let mainCode = '';
  for (const file of mainFiles) {
    const filePath = file.startsWith('shared/') ? path.join(rootDir, file) : path.join(extSrcDir, file);
    if (!fs.existsSync(filePath)) {
      console.error(`Error: Main component file ${file} not found at ${filePath}`);
      return false;
    }
    mainCode += `// --- Component: ${file} ---\n` + fs.readFileSync(filePath, 'utf8') + '\n\n';
  }

  const destIsolated = path.join(rootDir, 'yandex-sync-extension', 'isolated.js');
  fs.writeFileSync(destIsolated, isolatedCode, 'utf8');
  console.log(`Successfully built Extension isolated.js -> ${destIsolated}`);

  // Bundle soundcloud-bridge.js as standalone isolated script with shared/soundcloud-import.js
  const bridgeSrc = path.join(extSrcDir, 'isolated', 'soundcloud-bridge.js');
  const sharedImport = path.join(rootDir, 'shared', 'soundcloud-import.js');
  const bridgeDest = path.join(rootDir, 'yandex-sync-extension', 'soundcloud-bridge.js');
  if (fs.existsSync(bridgeSrc) && fs.existsSync(sharedImport)) {
    const combined = fs.readFileSync(sharedImport, 'utf8') + '\n\n' + fs.readFileSync(bridgeSrc, 'utf8');
    fs.writeFileSync(bridgeDest, combined, 'utf8');
    console.log(`Successfully built bundled soundcloud-bridge.js -> ${bridgeDest}`);
  }

  const destMain = path.join(rootDir, 'yandex-sync-extension', 'main.js');
  fs.writeFileSync(destMain, mainCode, 'utf8');
  console.log(`Successfully built Extension main.js -> ${destMain}`);

  return true;
}

function main() {
  bundleVibeStyles();

  const args = process.argv.slice(2);
  let buildEl = true;
  let buildExt = true;

  if (args.includes('--electron')) {
    buildExt = false;
  } else if (args.includes('--extension')) {
    buildEl = false;
  }

  let success = true;
  if (buildEl) {
    success = buildElectron() && success;
  }
  if (buildExt) {
    success = buildExtension() && success;
  }

  // Сборка сервера через ncc
  console.log('Building Standalone Server with ncc...');
  try {
    const { execSync } = require('child_process');
    execSync('npx ncc build server.js -o dist/server-bundle -m', { stdio: 'inherit', cwd: rootDir });
    console.log('Successfully built Standalone Server -> dist/server-bundle/index.js');
    
    // Copy it to installer assets
    const installerAssetsDir = path.join(rootDir, 'yandex-sync-installer', 'assets');
    if (fs.existsSync(installerAssetsDir)) {
      const destPath = path.join(installerAssetsDir, 'sync-server.bundle.js');
      fs.copyFileSync(path.join(rootDir, 'dist', 'server-bundle', 'index.js'), destPath);
      console.log(`Successfully copied sync-server.bundle.js -> ${destPath}`);
    }
  } catch (err) {
    console.error('Error building standalone server:', err.message);
    success = false;
  }

  if (!success) {
    process.exit(1);
  }
}

if (require.main === module) {
  main();
}

module.exports = {
  buildElectron,
  buildExtension
};
